### ISSUE TITLE
Should set appropriate MIME type in setup.py for reStructred text README

### ISSUE THREAD

**Issue by agathver** [Nancy-Chauhan/pyinit#2]
If I specify type of README to be reStructured text, the MIME type in `long_description_type` in `setup.py` is still `text/markdown`. 

It should be `text/x-rst`

https://packaging.python.org/guides/making-a-pypi-friendly-readme/

**Comment by Nancy-Chauhan** [comment]
Resolved here :
 https://github.com/Nancy-Chauhan/pyinit/commit/b2b7d6de81f489a186285de46b4731186b82cd5f
